<?php if ($this->isAvailable()) : ?>

<?php $financeEnvironment =  Mage::helper('finance_pay')->financeEnvironment; ?>

<div class="divido-widget">
    <div id="financeCalculator" data-calculator-widget 
    <?php echo $this->popupOrNot(); ?>
    data-plans="<?php echo $this->getPlans(); ?>" 
    data-amount="<?php echo $this->getPrice(); ?>" ></div>
</div>
<?php endif; ?>
<script>
//<![CDATA[
//]]>
</script>