<?php if ($this->isAvailable()) : ?>

<?php $financeEnvironment =  Mage::helper('finance_pay')->financeEnvironment; ?>

<div class="divido-widget">
    <div data-<?php echo $financeEnvironment ?>-widget <?php echo $this->popupOrNot(); ?> data-<?php echo $financeEnvironment ?>-plans="<?php echo $this->getPlans(); ?>" data-<?php echo $financeEnvironment ?>-amount="<?php echo $this->getPrice(); ?>"></div>
</div>
<?php endif; ?>
